"use strict";

// eslint-disable-next-line no-unused-vars
function changeColor(r, col) {
	r.style.backgroundColor = col;
}

var res, b_green, b_red;

res = document.querySelector("div#res");
window.onload = res.innerHTML = "This text was generated by JavaScript...";
b_green = document.createElement("button");
b_green.innerHTML = "green";
b_green.setAttribute("onclick", "changeColor(res, 'green')");
document.body.appendChild(b_green);
b_red = document.createElement("button");
b_red.innerHTML = "red";
b_red.setAttribute("onclick", "changeColor(res, 'red')");
document.body.appendChild(b_red);

